version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Ljfjiayou553592
    ports:
      - "3306:3306"
    volumes:
      - /volume2/homes/2410632887/mysql:/var/lib/mysql
    networks:
      - app-network
  delay-server:
    container_name: my-site
    image: my-site
    ports:
      - "8089:8089"
    volumes:
      - "./tmp:/tmp"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_DRUID_URL: jdbc:mysql://mysql:3306/lu_tale?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      SPRING_DATASOURCE_DRUID_USERNAME: root
      SPRING_DATASOURCE_DRUID_PASSWORD: Ljfjiayou553592
      QINIU_ACCESSKEY: ""
      QINIU_SERECTKEY: ""
      QINIU_BUCKET: ""
      QINIU_CDN_URL: ""
networks:
  app-network:
    driver: bridge